/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CarsVehicleIdRouteImport } from './routes/cars.$vehicleId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CarsVehicleIdRoute = CarsVehicleIdRouteImport.update({
  id: '/cars/$vehicleId',
  path: '/cars/$vehicleId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cars/$vehicleId': typeof CarsVehicleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cars/$vehicleId': typeof CarsVehicleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cars/$vehicleId': typeof CarsVehicleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cars/$vehicleId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cars/$vehicleId'
  id: '__root__' | '/' | '/cars/$vehicleId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CarsVehicleIdRoute: typeof CarsVehicleIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cars/$vehicleId': {
      id: '/cars/$vehicleId'
      path: '/cars/$vehicleId'
      fullPath: '/cars/$vehicleId'
      preLoaderRoute: typeof CarsVehicleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CarsVehicleIdRoute: CarsVehicleIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
